AWSTemplateFormatVersion: "2010-09-09-OC"
Description: default template generated for organization with master account 398495949130

Organization:
  ManagementAccount:
    Type: OC::ORG::MasterAccount
    Properties:
      AccountName: root
      AccountId: "398495949130"
      RootEmail: aws+root@nourez.dev

  OrganizationRoot:
    Type: OC::ORG::OrganizationRoot
    Properties:
      DefaultOrganizationAccessRoleName: OrganizationAccountAccessRole

  SharedOU:
    Type: OC::ORG::OrganizationalUnit
    Properties:
      OrganizationalUnitName: shared
      Accounts:
        - !Ref SecurityAccount
        - !Ref ApplicationLoggingAccount
        - !Ref SharedServicesAccount

  DevelopmentOU:
    Type: OC::ORG::OrganizationalUnit
    Properties:
      OrganizationalUnitName: development
      Accounts:
        - !Ref CloudResumeDev

  ProductionOU:
    Type: OC::ORG::OrganizationalUnit
    Properties:
      OrganizationalUnitName: production
      Accounts:
        - !Ref CloudResumeProd

  SandboxOU:
    Type: OC::ORG::OrganizationalUnit
    Properties:
      OrganizationalUnitName: sandboxes
      Accounts:
        - !Ref SandboxAccount
        - !Ref TerraformSandboxAccount

  TerraformSandboxAccount:
    Type: OC::ORG::Account
    Properties:
      RootEmail: aws+terraformsandbox@nourez.dev
      AccountName: terraform-sandbox
      Tags:
        budget-alarm-threshold: "5"

  SandboxAccount:
    Type: OC::ORG::Account
    Properties:
      RootEmail: aws+sandbox@nourez.dev
      AccountName: sandbox
      Tags:
        budget-alarm-threshold: "15"

  SecurityAccount:
    Type: OC::ORG::Account
    Properties:
      RootEmail: aws+security@nourez.dev
      AccountName: security
      Tags:
        budget-alarm-threshold: "5"

  ApplicationLoggingAccount:
    Type: OC::ORG::Account
    Properties:
      RootEmail: aws+applogging@nourez.dev
      AccountName: application-logging
      Tags:
        budget-alarm-threshold: "5"

  SharedServicesAccount:
    Type: OC::ORG::Account
    Properties:
      RootEmail: aws+sharedservices@nourez.dev
      AccountName: shared-services
      Tags:
        budget-alarm-threshold: "5"

  CloudResumeDev:
    Type: OC::ORG::Account
    Properties:
      RootEmail: aws+cloudresumedev@nourez.dev
      AccountName: cloud-resume-dev
      Tags:
        budget-alarm-threshold: "10"
        project: "cloud-resume-challenge"

  CloudResumeProd:
    Type: OC::ORG::Account
    Properties:
      RootEmail: aws+cloudresumeprod@nourez.dev
      AccountName: cloud-resume-prod
      Tags:
        budget-alarm-threshold: "20"
